# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AuthorizationInfoParameters(Model):
    _attribute_map = {
        'authorization': {'key': 'Authorization', 'type': 'str'},
    }

    def __init__(self, authorization=None):
        self.authorization = authorization
