# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BuildConfiguration(Model):
    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'working_directory': {'key': 'workingDirectory', 'type': 'str'},
        'node_type': {'key': 'NodeJsTaskRunnerType', 'type': 'str'},
    }

    def __init__(self, type=None, working_directory=None, node_type=None):
        self.type = type
        self.working_directory = working_directory
        self.node_type = node_type
