# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProvisioningConfigurationSource(Model):
    _attribute_map = {
        'type': {'key': 'Type', 'type': 'str'},
        'repository': {'key': 'Repository', 'type': 'Repository'},
        'build_configuration': {'key': 'BuildConfiguration', 'type': 'str'},
    }

    def __init__(self, type=None, repository=None, build_configuration=None):
        self.type = type
        self.repository = repository
        self.build_configuration = build_configuration
