# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SourceRepository(Model):
    _attribute_map = {
        'type': {'key': 'Type', 'type': 'str'},
        'identifier': {'key': 'Identifier', 'type': 'str'},
        'default_branch': {'key': 'DefaultBranch', 'type': 'str'},
        'access_token': {'key': 'AccessToken', 'type': 'str'},
    }

    def __init__(self, type=None, identifier=None, default_branch=None, access_token = None):
        self.type = type
        self.identifier = identifier
        self.default_branch = default_branch
        self.access_token = access_token
