# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AccountRegion(Model):
    """AccountRegion.

    :param display_name: Display name of the account region
    :type display_name: str
    :param is_default: Whether the region is default or not
    :type is_default: bool
    :param location_name: Azure location name
    :type location_name: str
    """

    _attribute_map = {
        'display_name': {'key': 'displayName', 'type': 'str'},
        'is_default': {'key': 'isDefault', 'type': 'bool'},
        'location_name': {'key': 'locationName', 'type': 'str'},
    }

    def __init__(self, display_name=None, is_default=None, location_name=None):
        self.display_name = display_name
        self.is_default = is_default
        self.location_name = location_name
