# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AccountNameAvailability(Model):
    """AccountNameAvailability.

    :param is_valid_name:
    :type is_valid_name: bool
    :param status_reason: Reason for current status
    :type status_reason: str
    """

    _attribute_map = {
        'is_valid_name': {'key': 'isValidName', 'type': 'bool'},
        'status_reason': {'key': 'statusReason', 'type': 'str'},
    }

    def __init__(self, is_valid_name=None, status_reason=None):
        self.is_valid_name = is_valid_name
        self.status_reason = status_reason
