# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PropertiesCollection(Model):
    """PropertiesCollection.

    :param count: Implements ICollection<KeyValuePair<String,Object>>.Count/>
    :type count: int
    :param item:
    :type item: object
    :param keys:
    :type keys: list of str
    :param values:
    :type values: list of str
    """

    _attribute_map = {
        'count': {'key': 'count', 'type': 'int'},
        'item': {'key': 'item', 'type': 'object'},
        'keys': {'key': 'keys', 'type': '[str]'},
        'values': {'key': 'values', 'type': '[str]'},
    }

    def __init__(self, count=None, item=None, keys=None, values=None):
        self.count = count
        self.item = item
        self.keys = keys
        self.values = values
